title: Foo Bar
subtitle: Computer Science Blog
author:
  name: Dinah Johnson
  copyright-year: 2022
  email: dinahjohnson@pm.me
twitter_username: cybergirldinah
github_username:  dinahjohnson
linkedin_username: dinahjohnson
description: >-
  My collection of computer science research, project tutorials, problem solving
  practice, and musings on the latest technology trends.
 
url: "https://dinahjohnson.github.io" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: G-DGYQCSL3S6

header_pages:
  - blog.markdown
  - projects.markdown
  - about.markdown

# Build settings
theme: minima


    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
plugins:
  - jekyll-feed
  - jekyll-seo-tag